exclude: [vendor]
baseurl: /junest-site

name:         JuNest
description:  The lightweight Arch Linux based distro that runs, without root privileges, upon any Linux distro
url:          http://fsquillace.github.io/junest-site/

excerpt_separator: <!--more-->

gems:
      - jekyll-sitemap

theme: jekyll-theme-cayman